node{
    stage('clone'){
        //clean the workspace first
        cleanWs()
        //clone the repository
        git 'https://github.com/radhasable/advanced-terraform-2823489.git'
    }

    stage('Download'){
        //download terraform
        sh label: '', script: 'curl https://releases.hashicorp.com/terraform/0.12.29/terraform_0.12.29_linux_amd64.zip \
            --output terraform_0.12.29_darwin_amd64.zip \
             && unzip terraform_0.12.29_darwin_amd64.zip'
    }

    stage('Terraform init'){
        //initializa the terraform configuration
        dir('02_01_variables'){
            sh script: '../terraform init -input=false'
        }
    }

    stage('terraform plan'){
        //create terraform plan for the resources
        withCredentials([string(credentialsId: 'AWS_ACCESS_KEY', variable: 'aws_access_key'), 
        string(credentialsId: 'AWS_SECRET_KEY', variable: 'aws_secret_key')]) {
            dir('02_01_variables'){
                sh script: '../terraform plan \
                -out backend.tfplan \
                -var="aws_access_key=$aws_access_key" \
                -var="aws_secret_key=$aws_secret_key"'
            }
        }

    }

    stage('terraform apply'){
        //apply the terraform plan
        withCredentials([string(credentialsId: 'AWS_ACCESS_KEY', variable: 'aws_access_key'), 
        string(credentialsId: 'AWS_SECRET_KEY', variable: 'aws_secret_key')]) {
            dir('02_01_variables'){
                sh script: '../terraform apply \
                -auto-approve \
                -var="aws_access_key=$aws_access_key" \
                -var="aws_secret_key=$aws_secret_key"'
            }
        }
    }

    stage('terraform destroy'){
        //destroy the terraform changes
        input 'Destroy?'
        withCredentials([string(credentialsId: 'AWS_ACCESS_KEY', variable: 'aws_access_key'), 
        string(credentialsId: 'AWS_SECRET_KEY', variable: 'aws_secret_key')]) {
            dir('02_01_variables'){
                sh script: '../terraform destroy \
                -auto-approve \
                -var="aws_access_key=$aws_access_key" \
                -var="aws_secret_key=$aws_secret_key"'
            }
        }
    }
}